type JsonRecord = Record<string, unknown>;

export type GoldenTestData = ReturnType<typeof buildGoldenTestData>;

const createdAt = '2026-06-22T08:00:00.000Z';
const imageUrl = '/brand/product-experience-logo.png';

function taskContent(task: JsonRecord, title: string) {
  return {
    task,
    ai_summary: {
      tag: 'Golden Test',
      satisfaction_score: 7.8,
      summary: `${title}用于 Docker Golden Test 验收，覆盖报告中心、详情入口、证据位和后续 PDF 回归。`,
      strengths: ['结构化字段完整', '证据与问题可关联'],
      risks: ['存在待关闭问题，需要在报告中心突出'],
      suggestions: ['确认 AI 结论后发布快照'],
    },
    records: [
      {
        id: `${task.id}-record-1`,
        check_item: '外观与操作触点',
        evaluation_result: '不合格',
        problem_description: '触点边缘存在割手风险，需优化倒角。',
        standard_category: '通用标准',
        sensory_dimension: '触觉',
        problem_level: '一类',
        materials: [
          {
            id: `${task.id}-mat-1`,
            material_type: 'image',
            file_name: 'golden-evidence.png',
            file_url: imageUrl,
            file_path: imageUrl,
            file_size: 1024,
          },
        ],
      },
    ],
    issues: [],
    recipes: [
      {
        id: `${task.id}-recipe-1`,
        name: 'Golden Test 功能步骤',
        ingredients: '测试物料',
        recipe_type: '功能',
        problem_count: 1,
        effect_description: '出品状态可观察，存在轻微波动。',
        effect_problem_point: JSON.stringify([{ text: '效果稳定性需要复测', material_ids: [`${task.id}-mat-1`] }]),
        effect_ai_result: { score: 7.5, summary: '整体可接受，但稳定性需跟进。' },
        recipe_steps: [
          {
            id: `${task.id}-step-1`,
            step_number: 1,
            operation: '执行 Golden Test 标准步骤',
            problem_point: '步骤证据用于回归验证',
            problem_points: [{ text: '步骤证据用于回归验证', material_ids: [`${task.id}-step-mat-1`] }],
            materials: [
              {
                id: `${task.id}-step-mat-1`,
                material_type: 'image',
                file_name: 'golden-step-evidence.png',
                file_url: imageUrl,
                file_path: imageUrl,
                file_size: 1024,
                media_role: 'step_evidence',
              },
            ],
          },
        ],
        effect_materials: [
          {
            id: `${task.id}-mat-1`,
            material_type: 'image',
            file_name: 'golden-effect-evidence.png',
            file_url: imageUrl,
            file_path: imageUrl,
            file_size: 1024,
            media_role: 'effect_evidence',
          },
        ],
      },
    ],
    materials: [],
    generatedAt: createdAt,
  };
}

export function buildGoldenTestData(adminUserId: string) {
  const tasks = [
    {
      id: 'golden-task-single',
      task_name: 'GT-01 原汁机双口径指标表',
      product_category: '电动',
      product: '原汁机',
      product_model: 'GT-JUICE-120-160',
      project_number: 'GT-2026-001',
      project_type: 'ODM',
      project_phase: '试制阶段',
      test_date: '2026-06-22',
      organizer: 'Golden QA',
      created_by: adminUserId,
      target_user: '体验工程师',
      test_purpose: '验证双口径指标表和报告中心交付状态。',
      test_method: '结构化录入 + 报告生成',
      status: '已完成',
      task_mode: 'single',
    },
    {
      id: 'golden-task-comparison',
      task_name: 'GT-02 三台 7L 和面机图片矩阵',
      product_category: '电动',
      product: '和面机',
      product_model: 'GT-HMJ-7L',
      project_number: 'GT-2026-002',
      project_type: '竞品研究',
      project_phase: '试制阶段',
      test_date: '2026-06-22',
      organizer: 'Golden QA',
      created_by: adminUserId,
      target_user: '体验工程师 / PM',
      test_purpose: '验证多对象对比矩阵、证据位和 AI 确认状态。',
      test_method: '对象列 x 项目行对比',
      status: '已完成',
      task_mode: 'comparison',
      comparison_intent: '横向比较三台 7L 和面机关键体验差异',
      comparison_layout_type: 'image_matrix',
      comparison_source: 'golden_test',
    },
    {
      id: 'golden-task-metric',
      task_name: 'GT-03 原汁机双口径指标对比',
      product_category: '电动',
      product: '原汁机',
      product_model: 'GT-JUICE-METRIC',
      project_number: 'GT-2026-003',
      project_type: 'ODM',
      project_phase: '试制阶段',
      test_date: '2026-06-22',
      organizer: 'Golden QA',
      created_by: adminUserId,
      target_user: '产品工程师 / PM',
      test_purpose: '验证出汁率、纯汁率、含渣率等指标型对比报告。',
      test_method: '对象列 x 指标行对比',
      status: '已完成',
      task_mode: 'comparison',
      comparison_intent: '横向比较 120mm 与 160mm 口径原汁机关键指标差异',
      comparison_layout_type: 'metric_table',
      comparison_source: 'golden_test',
    },
    {
      id: 'golden-task-model-a',
      task_name: 'GT-03 球形桶和面机阶段演进-试制',
      product_category: '电动',
      product: '和面机',
      product_model: 'GT-SPHERE-HMJ',
      project_number: 'GT-2026-003A',
      project_type: '自研',
      project_phase: '试制阶段',
      test_date: '2026-06-22',
      organizer: 'Golden QA',
      created_by: adminUserId,
      target_user: '体验负责人',
      test_purpose: '验证型号合并报告阶段轴数据。',
      test_method: '阶段报告合并',
      status: '已完成',
      task_mode: 'single',
    },
    {
      id: 'golden-task-custom',
      task_name: 'GT-04 自定义历史报告合并',
      product_category: '电动',
      product: '厨房电器',
      product_model: 'GT-CUSTOM-TOPIC',
      project_number: 'GT-2026-004',
      project_type: '前期研究',
      project_phase: '专题复盘',
      test_date: '2026-06-22',
      organizer: 'Golden QA',
      created_by: adminUserId,
      target_user: '体验负责人 / 研发',
      test_purpose: '验证自定义合并报告和可比性边界提示。',
      test_method: '多报告专题汇总',
      status: '已完成',
      task_mode: 'single',
    },
  ];

  const reports = [
    {
      id: 'golden-report-single',
      task_id: 'golden-task-single',
      title: 'GT-01 原汁机双口径指标表报告',
      product_model: 'GT-JUICE-120-160',
      organizer: 'Golden QA',
      project_type: 'ODM',
      project_phase: '试制阶段',
      status: '已完成',
      version: 1,
      created_by: adminUserId,
      content: taskContent(tasks[0], 'GT-01 原汁机双口径指标表报告'),
      report_type: 'single_report',
      source_task_ids: ['golden-task-single'],
      source_report_ids: [],
      assembly_id: null,
      snapshot_id: null,
      layout_profile: 'single_a4_portrait',
      ai_confirmation_status: 'confirmed',
    },
    {
      id: 'golden-report-comparison',
      task_id: 'golden-task-comparison',
      title: 'GT-02 三台 7L 和面机图片矩阵报告',
      product_model: 'GT-HMJ-7L',
      organizer: 'Golden QA',
      project_type: '竞品研究',
      project_phase: '试制阶段',
      status: '草稿',
      version: 1,
      created_by: adminUserId,
      content: null,
      report_type: 'comparison_report',
      source_task_ids: ['golden-task-comparison'],
      source_report_ids: [],
      assembly_id: 'golden-assembly-hmj',
      snapshot_id: 'golden-snapshot-comparison',
      layout_profile: 'comparison_image_matrix_a3_landscape',
      ai_confirmation_status: 'pending',
    },
    {
      id: 'golden-report-metric',
      task_id: 'golden-task-metric',
      title: 'GT-03 原汁机双口径指标对比报告',
      product_model: 'GT-JUICE-METRIC',
      organizer: 'Golden QA',
      project_type: 'ODM',
      project_phase: '试制阶段',
      status: '草稿',
      version: 1,
      created_by: adminUserId,
      content: null,
      report_type: 'comparison_report',
      source_task_ids: ['golden-task-metric'],
      source_report_ids: [],
      assembly_id: 'golden-assembly-juicer-metric',
      snapshot_id: 'golden-snapshot-metric',
      layout_profile: 'comparison_metric_table_a3_landscape',
      ai_confirmation_status: 'generated',
    },
    {
      id: 'golden-report-model',
      task_id: 'golden-task-model-a',
      title: 'GT-03 球形桶和面机阶段演进报告',
      product_model: 'GT-SPHERE-HMJ',
      organizer: 'Golden QA',
      project_type: '自研',
      project_phase: '试制阶段',
      status: '已发布',
      version: 1,
      created_by: adminUserId,
      content: taskContent(tasks[3], 'GT-03 球形桶和面机阶段演进报告'),
      report_type: 'model_merged_report',
      source_task_ids: ['golden-task-model-a'],
      source_report_ids: ['golden-report-single'],
      assembly_id: null,
      snapshot_id: 'golden-snapshot-model',
      layout_profile: 'model_merged_a4_portrait',
      ai_confirmation_status: 'confirmed',
    },
    {
      id: 'golden-report-custom',
      task_id: 'golden-task-custom',
      title: 'GT-04 自定义历史报告合并',
      product_model: 'GT-CUSTOM-TOPIC',
      organizer: 'Golden QA',
      project_type: '前期研究',
      project_phase: '专题复盘',
      status: '已完成',
      version: 1,
      created_by: adminUserId,
      content: taskContent(tasks[4], 'GT-04 自定义历史报告合并'),
      report_type: 'custom_merged_report',
      source_task_ids: ['golden-task-single', 'golden-task-custom'],
      source_report_ids: ['golden-report-single', 'golden-report-model'],
      assembly_id: null,
      snapshot_id: null,
      layout_profile: 'custom_merged_a4_portrait',
      ai_confirmation_status: 'confirmed',
    },
  ];

  const records = tasks.map((task) => ({
    id: `${task.id}-record-1`,
    task_id: task.id,
    standard_category: '通用标准',
    sensory_dimension: '触觉',
    test_phase: '产品使用',
    experience_flow: '操作交互',
    touch_point: '操作边缘',
    check_item: '触点安全性',
    check_requirement: '边缘不应割手，操作反馈清晰',
    evaluation_result: '不合格',
    problem_description: '边缘存在割手风险，需优化倒角。',
    problem_level: '一类',
    tester: 'Golden QA',
  }));

  const issues = reports.map((report, index) => ({
    id: `golden-issue-${index + 1}`,
    task_id: report.task_id,
    record_id: `${report.task_id}-record-1`,
    title: `${report.title} - 高风险问题`,
    product_model: report.product_model,
    category: '触觉',
    level: index === 0 ? '一类' : '二类',
    source: 'golden_test',
    source_report_id: report.id,
    source_type: 'record_fail',
    description: 'Golden Test 用于验证报告中心高风险未关闭问题。',
    is_improve: true,
    improve_plan: '优化结构并补充复测证据。',
    responsible_dept: '体验工程',
    responsible_person: 'Golden Owner',
    status: index === 2 ? '已验证' : '待整改',
  }));

  const materials = tasks.map((task) => ({
    id: `${task.id}-mat-1`,
    record_id: `${task.id}-record-1`,
    recipe_step_id: null,
    task_id: task.id,
    issue_id: null,
    re_evaluation_id: null,
    material_type: 'image',
    file_name: 'golden-evidence.png',
    file_path: imageUrl,
    file_url: imageUrl,
    file_size: 1024,
    ai_analysis_status: 'pending',
    media_role: 'inline_evidence',
    media_display_order: 1,
  }));
  const reEvaluationMaterials = [
    {
      id: 'golden-re-evaluation-mat-1',
      record_id: null,
      recipe_step_id: null,
      task_id: 'golden-task-single',
      issue_id: 'golden-issue-1',
      re_evaluation_id: 'golden-re-evaluation-1',
      material_type: 'image',
      file_name: 'golden-re-evaluation-evidence.png',
      file_path: imageUrl,
      file_url: imageUrl,
      file_size: 1024,
      ai_analysis_status: 'pending',
      media_role: 're_evaluation_evidence',
      media_display_order: 2,
    },
  ];
  const issueReEvaluations = [
    {
      id: 'golden-re-evaluation-1',
      issue_id: 'golden-issue-1',
      description: 'Golden 复评估显示整改后波动收敛，但仍需下一阶段复测。',
      ai_result: { score: 8, summary: '整改后表现改善，建议保留下一轮验证。' },
      created_by: adminUserId,
    },
  ];
  const stepMaterials = tasks.map((task, index) => ({
    id: `${task.id}-step-mat-1`,
    record_id: null,
    recipe_step_id: `golden-step-${index + 1}`,
    task_id: task.id,
    issue_id: null,
    re_evaluation_id: null,
    material_type: 'image',
    file_name: 'golden-step-evidence.png',
    file_path: imageUrl,
    file_url: imageUrl,
    file_size: 1024,
    ai_analysis_status: 'pending',
    media_role: 'step_evidence',
    media_display_order: 3,
  }));

  const recipes = tasks.map((task) => ({
    id: `${task.id}-recipe-1`,
    task_id: task.id,
    name: `${task.product} Golden 功能`,
    ingredients: '测试物料',
    recipe_type: '功能',
    problem_count: 1,
    effect_description: '出品状态可观察，存在轻微波动。',
    effect_score: '7.5',
    effect_problem_point: JSON.stringify([{ text: '效果稳定性需要复测', material_ids: [`${task.id}-mat-1`] }]),
    effect_ai_result: { score: 7.5, summary: '整体可接受，但稳定性需跟进。' },
  }));

  const recipeSteps = recipes.map((recipe, index) => ({
    id: `golden-step-${index + 1}`,
    recipe_id: recipe.id,
    step_number: 1,
    operation: '执行 Golden Test 标准步骤',
    problem_point: '步骤证据用于回归验证',
    problem_points: [{ text: '步骤证据用于回归验证', material_ids: [stepMaterials[index].id] }],
  }));

  const comparison = {
    assembly: {
      id: 'golden-assembly-hmj',
      name: 'GT-02 三台 7L 和面机图片矩阵',
      assembly_type: 'task_comparison',
      source_type: 'task',
      product_category: '电动',
      product: '和面机',
      comparison_intent: '横向比较三台 7L 和面机关键体验差异',
      layout_type: 'image_matrix',
      status: 'draft',
      source_task_ids: ['golden-task-comparison'],
      source_report_ids: [],
      created_by: adminUserId,
    },
    objects: [
      { id: 'golden-object-a', assembly_id: 'golden-assembly-hmj', task_id: 'golden-task-comparison', object_name: 'A款 7L 和面机', object_type: 'prototype', model: 'GT-HMJ-A', sort_order: 1 },
      { id: 'golden-object-b', assembly_id: 'golden-assembly-hmj', task_id: 'golden-task-comparison', object_name: 'B款 7L 和面机', object_type: 'competitor', model: 'GT-HMJ-B', is_competitor: true, sort_order: 2 },
      { id: 'golden-object-c', assembly_id: 'golden-assembly-hmj', task_id: 'golden-task-comparison', object_name: 'C款 7L 和面机', object_type: 'competitor', model: 'GT-HMJ-C', is_competitor: true, sort_order: 3 },
    ],
    itemNodes: [
      { id: 'golden-node-noodle', assembly_id: 'golden-assembly-hmj', node_type: 'item', node_label: '中式面团效果', sort_order: 1, depth: 0 },
      { id: 'golden-node-noise', assembly_id: 'golden-assembly-hmj', node_type: 'metric', node_label: '运行噪音', sort_order: 2, depth: 0 },
    ],
    cells: [
      { id: 'golden-cell-a-noodle', assembly_id: 'golden-assembly-hmj', item_node_id: 'golden-node-noodle', object_id: 'golden-object-a', effect_summary: '成团稳定，表面较光滑', manual_score: '8.0', conclusion_tag: 'best', problem_points: [] },
      { id: 'golden-cell-b-noodle', assembly_id: 'golden-assembly-hmj', item_node_id: 'golden-node-noodle', object_id: 'golden-object-b', effect_summary: '成团略慢，边缘粘附', manual_score: '6.8', conclusion_tag: 'risk', problem_points: ['边缘粘附明显'] },
      { id: 'golden-cell-a-noise', assembly_id: 'golden-assembly-hmj', item_node_id: 'golden-node-noise', object_id: 'golden-object-a', effect_summary: '运行噪音可接受', manual_score: '7.5', conclusion_tag: 'acceptable', problem_points: [] },
      { id: 'golden-cell-b-noise', assembly_id: 'golden-assembly-hmj', item_node_id: 'golden-node-noise', object_id: 'golden-object-b', effect_summary: '高转速噪音偏大', manual_score: '6.0', conclusion_tag: 'risk', problem_points: ['高转速噪音偏大'] },
    ].map((cell) => ({
      ...cell,
      ai_status: cell.conclusion_tag === 'risk' ? 'generated' : 'confirmed',
      anomaly_reason: cell.id === 'golden-cell-b-noise' ? '高转速噪音超过同组均值' : undefined,
      inline_media: cell.id.includes('noodle') ? [{
        id: `${cell.id}-media`,
        material_type: 'image',
        file_name: `${cell.id}.png`,
        file_url: imageUrl,
        file_path: imageUrl,
        media_role: 'cell_evidence',
      }] : [],
    })),
  };

  const metricComparison = {
    assembly: {
      id: 'golden-assembly-juicer-metric',
      name: 'GT-03 原汁机双口径指标对比',
      assembly_type: 'task_comparison',
      source_type: 'task',
      product_category: '电动',
      product: '原汁机',
      comparison_intent: '横向比较 120mm 与 160mm 口径原汁机关键指标差异',
      layout_type: 'metric_table',
      status: 'draft',
      source_task_ids: ['golden-task-metric'],
      source_report_ids: [],
      created_by: adminUserId,
    },
    objects: [
      { id: 'golden-metric-object-120', assembly_id: 'golden-assembly-juicer-metric', task_id: 'golden-task-metric', object_name: '120mm 口径原汁机', object_type: 'prototype', model: 'GT-JUICE-120', sort_order: 1 },
      { id: 'golden-metric-object-160', assembly_id: 'golden-assembly-juicer-metric', task_id: 'golden-task-metric', object_name: '160mm 口径原汁机', object_type: 'variant', model: 'GT-JUICE-160', sort_order: 2 },
    ],
    itemNodes: [
      { id: 'golden-metric-node-yield', assembly_id: 'golden-assembly-juicer-metric', node_type: 'metric', node_label: '出汁率', sort_order: 1, depth: 0 },
      { id: 'golden-metric-node-purity', assembly_id: 'golden-assembly-juicer-metric', node_type: 'metric', node_label: '纯汁率', sort_order: 2, depth: 0 },
      { id: 'golden-metric-node-residue', assembly_id: 'golden-assembly-juicer-metric', node_type: 'metric', node_label: '含渣率', sort_order: 3, depth: 0 },
    ],
    cells: [
      {
        id: 'golden-metric-cell-120-yield',
        assembly_id: 'golden-assembly-juicer-metric',
        item_node_id: 'golden-metric-node-yield',
        object_id: 'golden-metric-object-120',
        metric_value: '68.5%',
        manual_score: '8.2',
        effect_summary: '出汁率达到阈值',
        conclusion_tag: 'acceptable',
        problem_points: [],
      },
      {
        id: 'golden-metric-cell-160-yield',
        assembly_id: 'golden-assembly-juicer-metric',
        item_node_id: 'golden-metric-node-yield',
        object_id: 'golden-metric-object-160',
        metric_value: '72.1%',
        manual_score: '8.8',
        effect_summary: '出汁率更优',
        conclusion_tag: 'best',
        problem_points: [],
      },
      {
        id: 'golden-metric-cell-120-purity',
        assembly_id: 'golden-assembly-juicer-metric',
        item_node_id: 'golden-metric-node-purity',
        object_id: 'golden-metric-object-120',
        metric_value: '91.0%',
        manual_score: '7.8',
        effect_summary: '纯汁率可接受',
        conclusion_tag: 'acceptable',
        problem_points: [],
      },
      {
        id: 'golden-metric-cell-160-residue',
        assembly_id: 'golden-assembly-juicer-metric',
        item_node_id: 'golden-metric-node-residue',
        object_id: 'golden-metric-object-160',
        metric_value: '4.8%',
        manual_score: '6.4',
        effect_summary: '含渣率接近上限，需要复测',
        conclusion_tag: 'risk',
        problem_points: ['含渣率接近阈值上限'],
      },
    ].map((cell) => ({
      ...cell,
      ai_status: cell.conclusion_tag === 'risk' ? 'generated' : 'confirmed',
      anomaly_reason: cell.conclusion_tag === 'risk' ? '含渣率接近阈值上限' : undefined,
      inline_media: cell.id === 'golden-metric-cell-120-yield' || cell.conclusion_tag === 'risk' ? [{
        id: `${cell.id}-media`,
        material_type: 'image',
        file_name: `${cell.id}.png`,
        file_url: imageUrl,
        file_path: imageUrl,
        media_role: 'cell_evidence',
      }] : [],
    })),
  };

  const snapshots = [
    {
      id: 'golden-snapshot-comparison',
      report_id: 'golden-report-comparison',
      report_type: 'comparison_report',
      version: 1,
      snapshot_json: {
        report_type: 'comparison_report',
        layout_profile: 'comparison_image_matrix_a3_landscape',
        assembly: comparison.assembly,
        objects: comparison.objects,
        item_nodes: comparison.itemNodes,
        cells: comparison.cells,
        primary_task_id: 'golden-task-comparison',
        source_task_ids: ['golden-task-comparison'],
        source_report_ids: [],
      },
      layout_profile: 'comparison_image_matrix_a3_landscape',
      created_by: adminUserId,
    },
    {
      id: 'golden-snapshot-metric',
      report_id: 'golden-report-metric',
      report_type: 'comparison_report',
      version: 1,
      snapshot_json: {
        report_type: 'comparison_report',
        layout_profile: 'comparison_metric_table_a3_landscape',
        assembly: metricComparison.assembly,
        objects: metricComparison.objects,
        item_nodes: metricComparison.itemNodes,
        cells: metricComparison.cells,
        metric_definitions: [
          { key: 'yield_rate', label: '出汁率', formula: '出汁重量 / 原料重量', threshold: '>= 68%' },
          { key: 'purity_rate', label: '纯汁率', formula: '纯汁重量 / 总汁重量', threshold: '>= 90%' },
          { key: 'residue_rate', label: '含渣率', formula: '渣重 / 原料重量', threshold: '<= 5%' },
        ],
        primary_task_id: 'golden-task-metric',
        source_task_ids: ['golden-task-metric'],
        source_report_ids: [],
      },
      layout_profile: 'comparison_metric_table_a3_landscape',
      created_by: adminUserId,
    },
    {
      id: 'golden-snapshot-model',
      report_id: 'golden-report-model',
      report_type: 'model_merged_report',
      version: 1,
      snapshot_json: {
        report_type: 'model_merged_report',
        layout_profile: 'model_merged_a4_portrait',
        source_report_ids: ['golden-report-single', 'golden-report-model'],
        source_task_ids: ['golden-task-single', 'golden-task-model-a'],
        comparability_statement: 'Golden model stages are connected by product model and stage metadata. Treat the dossier as longitudinal evidence, not a direct source ranking.',
        stages: [
          {
            stage: 'Trial build',
            report_id: 'golden-report-single',
            report_title: 'GT-01 source baseline',
            task_id: 'golden-task-single',
            task_name: 'GT-01 source baseline task',
            test_date: '2026-06-22',
            status: 'published',
            source_report_id: 'golden-report-single',
          },
          {
            stage: 'Pilot validation',
            report_id: 'golden-report-model',
            report_title: 'GT-03 model evolution report',
            task_id: 'golden-task-model-a',
            task_name: 'GT-03 model stage task',
            test_date: '2026-06-22',
            status: 'published',
            source_report_id: 'golden-report-model',
          },
        ],
        issue_evolution: [
          {
            stage: 'Trial build',
            issue: 'Touch edge risk',
            level: 'A',
            status: 'open',
            action: 'Optimize edge radius and retest in next build.',
            evidence: 'golden-report-single',
          },
          {
            stage: 'Pilot validation',
            issue: 'Touch edge risk',
            level: 'B',
            status: 'improving',
            action: 'Keep validation evidence in the next stage.',
            evidence: 'golden-report-model',
          },
        ],
        function_effect_evolution: [
          {
            stage: 'Trial build',
            name: 'Kneading stability',
            effect_description: 'Baseline function effect has mild fluctuation.',
            effect_score: '7.2',
            source_report_id: 'golden-report-single',
          },
          {
            stage: 'Pilot validation',
            name: 'Kneading stability',
            effect_description: 'Stability improved but still needs repeat verification.',
            effect_score: '7.8',
            source_report_id: 'golden-report-model',
          },
        ],
        current_risks: ['Open touch edge risk still needs next-stage validation evidence.'],
        next_validation_items: ['Retest the edge touch point after radius adjustment.', 'Keep effect stability samples aligned across stages.'],
      },
      layout_profile: 'model_merged_a4_portrait',
      created_by: adminUserId,
    },
  ];

  const pdfJobs = [
    {
      id: 'golden-pdf-failed',
      report_id: 'golden-report-comparison',
      snapshot_id: 'golden-snapshot-comparison',
      layout_profile: 'comparison_image_matrix_a3_landscape',
      status: 'failed',
      preflight_result: { ok: false, errors: ['Golden Test simulated PDF failure'] },
      error_message: 'Golden Test simulated PDF failure',
      created_by: adminUserId,
    },
  ];

  return { tasks, reports, records, issues, issueReEvaluations, materials: [...materials, ...reEvaluationMaterials, ...stepMaterials], recipes, recipeSteps, comparison, metricComparison, snapshots, pdfJobs };
}
